[pytest]
testpaths =
    tests
    tardis
    publications/AMU-liquidity-premium
python_files =
    test_*.py
    markup_files.py
    process_pcp.py
    panel_regressions.py
python_functions =
    test_*
